const SET_TEST = 'SET_TEST';
const SET_ZERO = 'SET_ZERO';

// register user
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR'

// Auth User
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

export {
    SET_TEST,
    SET_ZERO,

    REGISTER_SUCCESS,
    REGISTER_ERROR,

    LOGIN_SUCCESS,
    LOGIN_ERROR
}